// Generated: curated set of common Lucide icons, verified against the installed
// lucide-react package. Lucide is the only icon library used in Cognition.
import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlignCenter,
  AlignLeft,
  AlignRight,
  ArrowDown,
  ArrowDownLeft,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  ArrowUpRight,
  AtSign,
  Award,
  Ban,
  BarChart3,
  Bell,
  BellOff,
  Bold,
  Bookmark,
  Briefcase,
  Bug,
  Building2,
  Calendar,
  Camera,
  ChartBar,
  ChartLine,
  ChartPie,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CircleX,
  Clipboard,
  ClipboardCheck,
  Clock,
  Cloud,
  Code,
  Cog,
  Columns3,
  Compass,
  Copy,
  Cpu,
  CreditCard,
  Crown,
  Database,
  DollarSign,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileText,
  Files,
  Filter,
  Flag,
  Flame,
  Folder,
  FolderOpen,
  Gift,
  GitBranch,
  GitCommit,
  GitPullRequest,
  Globe,
  GripVertical,
  Hammer,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  Home,
  Image,
  Info,
  Italic,
  Key,
  Laptop,
  LayoutDashboard,
  LayoutGrid,
  Link,
  Link2,
  List,
  ListChecks,
  ListFilter,
  Loader,
  LoaderCircle,
  Lock,
  LockOpen,
  LogIn,
  LogOut,
  Mail,
  Map,
  MapPin,
  Maximize2,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  MicOff,
  Minimize2,
  Minus,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Move,
  Music,
  Navigation,
  Package,
  Paintbrush,
  Palette,
  PanelLeft,
  Paperclip,
  Pause,
  Pencil,
  Phone,
  Pin,
  Play,
  Plug,
  Plus,
  Power,
  Printer,
  RefreshCw,
  Rocket,
  RotateCcw,
  RotateCw,
  Rows3,
  Save,
  Scissors,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingCart,
  SkipBack,
  SkipForward,
  SlidersHorizontal,
  Smartphone,
  Smile,
  Sparkles,
  SquarePen,
  Star,
  Sun,
  Table,
  Tag,
  Tags,
  Target,
  Terminal,
  ThumbsDown,
  ThumbsUp,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Truck,
  Underline,
  Upload,
  User,
  UserPlus,
  UserRound,
  Users,
  Video,
  Volume2,
  VolumeX,
  Wifi,
  Wrench,
  X,
  Zap,
  ZoomIn,
  ZoomOut,
} from "lucide-react";

export const icons: { name: string; Icon: LucideIcon }[] = [
  { name: "Activity", Icon: Activity },
  { name: "AlignCenter", Icon: AlignCenter },
  { name: "AlignLeft", Icon: AlignLeft },
  { name: "AlignRight", Icon: AlignRight },
  { name: "ArrowDown", Icon: ArrowDown },
  { name: "ArrowDownLeft", Icon: ArrowDownLeft },
  { name: "ArrowLeft", Icon: ArrowLeft },
  { name: "ArrowRight", Icon: ArrowRight },
  { name: "ArrowUp", Icon: ArrowUp },
  { name: "ArrowUpDown", Icon: ArrowUpDown },
  { name: "ArrowUpRight", Icon: ArrowUpRight },
  { name: "AtSign", Icon: AtSign },
  { name: "Award", Icon: Award },
  { name: "Ban", Icon: Ban },
  { name: "BarChart3", Icon: BarChart3 },
  { name: "Bell", Icon: Bell },
  { name: "BellOff", Icon: BellOff },
  { name: "Bold", Icon: Bold },
  { name: "Bookmark", Icon: Bookmark },
  { name: "Briefcase", Icon: Briefcase },
  { name: "Bug", Icon: Bug },
  { name: "Building2", Icon: Building2 },
  { name: "Calendar", Icon: Calendar },
  { name: "Camera", Icon: Camera },
  { name: "ChartBar", Icon: ChartBar },
  { name: "ChartLine", Icon: ChartLine },
  { name: "ChartPie", Icon: ChartPie },
  { name: "Check", Icon: Check },
  { name: "CheckCheck", Icon: CheckCheck },
  { name: "ChevronDown", Icon: ChevronDown },
  { name: "ChevronLeft", Icon: ChevronLeft },
  { name: "ChevronRight", Icon: ChevronRight },
  { name: "ChevronUp", Icon: ChevronUp },
  { name: "ChevronsUpDown", Icon: ChevronsUpDown },
  { name: "CircleAlert", Icon: CircleAlert },
  { name: "CircleCheck", Icon: CircleCheck },
  { name: "CircleHelp", Icon: CircleHelp },
  { name: "CircleX", Icon: CircleX },
  { name: "Clipboard", Icon: Clipboard },
  { name: "ClipboardCheck", Icon: ClipboardCheck },
  { name: "Clock", Icon: Clock },
  { name: "Cloud", Icon: Cloud },
  { name: "Code", Icon: Code },
  { name: "Cog", Icon: Cog },
  { name: "Columns3", Icon: Columns3 },
  { name: "Compass", Icon: Compass },
  { name: "Copy", Icon: Copy },
  { name: "Cpu", Icon: Cpu },
  { name: "CreditCard", Icon: CreditCard },
  { name: "Crown", Icon: Crown },
  { name: "Database", Icon: Database },
  { name: "DollarSign", Icon: DollarSign },
  { name: "Download", Icon: Download },
  { name: "ExternalLink", Icon: ExternalLink },
  { name: "Eye", Icon: Eye },
  { name: "EyeOff", Icon: EyeOff },
  { name: "File", Icon: File },
  { name: "FileText", Icon: FileText },
  { name: "Files", Icon: Files },
  { name: "Filter", Icon: Filter },
  { name: "Flag", Icon: Flag },
  { name: "Flame", Icon: Flame },
  { name: "Folder", Icon: Folder },
  { name: "FolderOpen", Icon: FolderOpen },
  { name: "Gift", Icon: Gift },
  { name: "GitBranch", Icon: GitBranch },
  { name: "GitCommit", Icon: GitCommit },
  { name: "GitPullRequest", Icon: GitPullRequest },
  { name: "Globe", Icon: Globe },
  { name: "GripVertical", Icon: GripVertical },
  { name: "Hammer", Icon: Hammer },
  { name: "HardDrive", Icon: HardDrive },
  { name: "Hash", Icon: Hash },
  { name: "Headphones", Icon: Headphones },
  { name: "Heart", Icon: Heart },
  { name: "Home", Icon: Home },
  { name: "Image", Icon: Image },
  { name: "Info", Icon: Info },
  { name: "Italic", Icon: Italic },
  { name: "Key", Icon: Key },
  { name: "Laptop", Icon: Laptop },
  { name: "LayoutDashboard", Icon: LayoutDashboard },
  { name: "LayoutGrid", Icon: LayoutGrid },
  { name: "Link", Icon: Link },
  { name: "Link2", Icon: Link2 },
  { name: "List", Icon: List },
  { name: "ListChecks", Icon: ListChecks },
  { name: "ListFilter", Icon: ListFilter },
  { name: "Loader", Icon: Loader },
  { name: "LoaderCircle", Icon: LoaderCircle },
  { name: "Lock", Icon: Lock },
  { name: "LockOpen", Icon: LockOpen },
  { name: "LogIn", Icon: LogIn },
  { name: "LogOut", Icon: LogOut },
  { name: "Mail", Icon: Mail },
  { name: "Map", Icon: Map },
  { name: "MapPin", Icon: MapPin },
  { name: "Maximize2", Icon: Maximize2 },
  { name: "Menu", Icon: Menu },
  { name: "MessageCircle", Icon: MessageCircle },
  { name: "MessageSquare", Icon: MessageSquare },
  { name: "Mic", Icon: Mic },
  { name: "MicOff", Icon: MicOff },
  { name: "Minimize2", Icon: Minimize2 },
  { name: "Minus", Icon: Minus },
  { name: "Monitor", Icon: Monitor },
  { name: "Moon", Icon: Moon },
  { name: "MoreHorizontal", Icon: MoreHorizontal },
  { name: "MoreVertical", Icon: MoreVertical },
  { name: "Move", Icon: Move },
  { name: "Music", Icon: Music },
  { name: "Navigation", Icon: Navigation },
  { name: "Package", Icon: Package },
  { name: "Paintbrush", Icon: Paintbrush },
  { name: "Palette", Icon: Palette },
  { name: "PanelLeft", Icon: PanelLeft },
  { name: "Paperclip", Icon: Paperclip },
  { name: "Pause", Icon: Pause },
  { name: "Pencil", Icon: Pencil },
  { name: "Phone", Icon: Phone },
  { name: "Pin", Icon: Pin },
  { name: "Play", Icon: Play },
  { name: "Plug", Icon: Plug },
  { name: "Plus", Icon: Plus },
  { name: "Power", Icon: Power },
  { name: "Printer", Icon: Printer },
  { name: "RefreshCw", Icon: RefreshCw },
  { name: "Rocket", Icon: Rocket },
  { name: "RotateCcw", Icon: RotateCcw },
  { name: "RotateCw", Icon: RotateCw },
  { name: "Rows3", Icon: Rows3 },
  { name: "Save", Icon: Save },
  { name: "Scissors", Icon: Scissors },
  { name: "Search", Icon: Search },
  { name: "Send", Icon: Send },
  { name: "Server", Icon: Server },
  { name: "Settings", Icon: Settings },
  { name: "Share2", Icon: Share2 },
  { name: "Shield", Icon: Shield },
  { name: "ShieldCheck", Icon: ShieldCheck },
  { name: "ShoppingCart", Icon: ShoppingCart },
  { name: "SkipBack", Icon: SkipBack },
  { name: "SkipForward", Icon: SkipForward },
  { name: "SlidersHorizontal", Icon: SlidersHorizontal },
  { name: "Smartphone", Icon: Smartphone },
  { name: "Smile", Icon: Smile },
  { name: "Sparkles", Icon: Sparkles },
  { name: "SquarePen", Icon: SquarePen },
  { name: "Star", Icon: Star },
  { name: "Sun", Icon: Sun },
  { name: "Table", Icon: Table },
  { name: "Tag", Icon: Tag },
  { name: "Tags", Icon: Tags },
  { name: "Target", Icon: Target },
  { name: "Terminal", Icon: Terminal },
  { name: "ThumbsDown", Icon: ThumbsDown },
  { name: "ThumbsUp", Icon: ThumbsUp },
  { name: "Timer", Icon: Timer },
  { name: "Trash2", Icon: Trash2 },
  { name: "TrendingDown", Icon: TrendingDown },
  { name: "TrendingUp", Icon: TrendingUp },
  { name: "TriangleAlert", Icon: TriangleAlert },
  { name: "Truck", Icon: Truck },
  { name: "Underline", Icon: Underline },
  { name: "Upload", Icon: Upload },
  { name: "User", Icon: User },
  { name: "UserPlus", Icon: UserPlus },
  { name: "UserRound", Icon: UserRound },
  { name: "Users", Icon: Users },
  { name: "Video", Icon: Video },
  { name: "Volume2", Icon: Volume2 },
  { name: "VolumeX", Icon: VolumeX },
  { name: "Wifi", Icon: Wifi },
  { name: "Wrench", Icon: Wrench },
  { name: "X", Icon: X },
  { name: "Zap", Icon: Zap },
  { name: "ZoomIn", Icon: ZoomIn },
  { name: "ZoomOut", Icon: ZoomOut },
];
